export type DocExample = {
  title?: string;
  filename?: string;
  code: string;
};

export type DocSection = {
  heading: string;
  body: string[];
  bullets?: string[];
  note?: string;
  warning?: string;
  examples?: DocExample[];
};

export type DocPage = {
  slug: string;
  title: string;
  summary: string;
  category: string;
  sections: DocSection[];
};

export const docCategories = [
  'Start',
  'Core concepts',
  'Server',
  'Client',
  'Deployment',
  'Production'
] as const;

export const docs: DocPage[] = [
  {
    slug: 'getting-started',
    title: 'Getting Started',
    summary: 'Create a Blokd app on Web Platform primitives with SSR routes, native forms, Hono, and optional islands.',
    category: 'Start',
    sections: [
      {
        heading: 'Install',
        body: [
          'Blokd is named for the browser and Web API building blocks it uses directly. It is published as a small package with Hono as the HTTP layer, while Vite handles JSX transform, route discovery, and client/Worker builds.',
          'The beta is designed for TypeScript-first apps, but route modules stay close to standard Web APIs: Request, Response, FormData, URL, Headers, and fetch.'
        ],
        examples: [
          {
            code: 'pnpm add blokd hono\npnpm add -D vite typescript'
          }
        ]
      },
      {
        heading: 'Create the Hono app',
        body: [
          'A Blokd application is still a normal Hono app. Add API routes and middleware first, then mount the generated page router with createPages().',
          'The route manifest is generated by the Vite plugin from files in src/routes.'
        ],
        examples: [
          {
            filename: 'src/worker.ts',
            code: "import { Hono } from 'hono';\nimport { createPages } from 'blokd/hono';\nimport routes from 'virtual:blokd/routes';\n\nconst app = new Hono();\n\napp.get('/api/health', c => c.json({ ok: true }));\napp.route('/', createPages({ routes, entryClient: '/assets/client.js' }));\n\nexport default app;"
          }
        ]
      },
      {
        heading: 'Add the Vite plugin',
        body: [
          'The blokd() Vite plugin compiles JSX and produces virtual:blokd/routes. The default route directory is src/routes.',
          'For Cloudflare Workers, build the client CSS/assets separately from the Worker SSR entry.'
        ],
        examples: [
          {
            filename: 'vite.config.ts',
            code: "import { defineConfig } from 'vite';\nimport { blokd } from 'blokd/vite';\n\nexport default defineConfig({\n  plugins: [blokd()],\n  build: {\n    ssr: 'src/worker.ts',\n    outDir: 'dist/worker'\n  }\n});"
          }
        ]
      },
      {
        heading: 'Create your first page',
        body: [
          'Routes are JSX modules. A default export renders the page. Optional loader, action, meta, and headers exports extend the route.',
          'Routes without client markers render HTML and CSS without Blokd client JavaScript.'
        ],
        examples: [
          {
            filename: 'src/routes/index.tsx',
            code: "export const meta = () => ({\n  title: 'Home',\n  description: 'A Blokd page rendered on the server.'\n});\n\nexport default function HomePage() {\n  return <h1>Hello from Blokd</h1>;\n}"
          }
        ]
      }
    ]
  },
  {
    slug: 'project-structure',
    title: 'Project Structure',
    summary: 'A practical file layout for Blokd apps with routes, layouts, resumable handlers, and Workers output.',
    category: 'Start',
    sections: [
      {
        heading: 'Recommended layout',
        body: [
          'Blokd does not require a heavy application shell. Keep server code, route modules, client entry code, and resumable handler modules separate so the build can reason about what belongs in the browser.'
        ],
        examples: [
          {
            code: 'src/\n  worker.ts\n  client.ts\n  routes/\n    _layout.tsx\n    _error.tsx\n    _404.tsx\n    index.tsx\n    reservations.tsx\n    docs/\n      [slug].tsx\n  components/\n    SiteShell.tsx\n    ReservationForm.tsx\n  resumables/\n    estimate.ts\n  styles.css\nvite.config.ts\nvite.client.config.ts\nwrangler.jsonc'
          }
        ]
      },
      {
        heading: 'What goes where',
        body: [
          'Route modules own URL behavior. Components own reusable markup. Resumable modules own browser event handlers. The Hono app owns middleware, API routes, and deployment-specific bindings.',
          'This separation keeps static SSR pages free of accidental browser code.'
        ],
        bullets: [
          'Use src/routes for file-based page routes and private boundary files.',
          'Use src/components for JSX components shared by routes.',
          'Use src/resumables for event handlers registered from the client entry.',
          'Use src/worker.ts or src/server.ts for Hono middleware, API endpoints, and createPages().',
          'Use src/client.ts only for browser entry code such as startResumability().'
        ]
      },
      {
        heading: 'Build outputs',
        body: [
          'The Cloudflare example emits static assets to dist/client and the SSR Worker entry to dist/worker/entry-worker.js.',
          'Other hosts can use different folders, but the core split should remain: static assets are served directly, document requests go through Hono and Blokd.'
        ]
      }
    ]
  },
  {
    slug: 'routing',
    title: 'File Routing',
    summary: 'Map route files to URLs, use dynamic parameters, and keep layouts and boundaries private.',
    category: 'Core concepts',
    sections: [
      {
        heading: 'Route file mapping',
        body: [
          'Blokd turns files in src/routes into URL paths. index files map to their directory path. Files and folders wrapped in square brackets create route parameters.',
          'Private files beginning with _layout, _error, and _404 are used by the router but are not public pages.'
        ],
        examples: [
          {
            code: 'src/routes/index.tsx          -> /\nsrc/routes/about.tsx          -> /about\nsrc/routes/docs/index.tsx     -> /docs\nsrc/routes/docs/[slug].tsx    -> /docs/:slug\nsrc/routes/files/[...path].tsx -> /files/:path*'
          }
        ]
      },
      {
        heading: 'Dynamic params',
        body: [
          'Loader, action, meta, headers, and page components receive decoded route params. If a segment cannot be decoded safely, the route does not match.'
        ],
        examples: [
          {
            filename: 'src/routes/docs/[slug].tsx',
            code: "import { notFound } from 'blokd/server';\n\nexport const loader = async ({ params }) => {\n  const doc = await loadDoc(params.slug);\n  if (!doc) notFound();\n  return { doc };\n};\n\nexport default function DocPage(props) {\n  return <article><h1>{props.data.doc.title}</h1></article>;\n}"
          }
        ]
      },
      {
        heading: 'Route ordering',
        body: [
          'Static routes are preferred over dynamic routes. Dynamic and catch-all routes are scored so the most specific path wins.',
          'The Vite plugin fails the build when two route files map to the same URL path.'
        ]
      }
    ]
  },
  {
    slug: 'loaders-and-data',
    title: 'Loaders and Data',
    summary: 'Load server data with Web APIs and consume it in pages, layouts, metadata, and data requests.',
    category: 'Core concepts',
    sections: [
      {
        heading: 'Loader arguments',
        body: [
          'A loader runs for GET and HEAD document requests. It receives the raw Request, route params, and the Hono context.',
          'Return a plain object when you want its keys merged into route data. Return any other value when you want it stored under a fallback key.'
        ],
        examples: [
          {
            filename: 'src/routes/products/[slug].tsx',
            code: "export const loader = async ({ request, params, ctx }) => {\n  const product = await ctx.get('catalog').find(params.slug);\n  const url = new URL(request.url);\n  return {\n    product,\n    preview: url.searchParams.get('preview') === '1'\n  };\n};\n\nexport default function ProductPage(props) {\n  return <h1>{props.data.product.name}</h1>;\n}"
          }
        ]
      },
      {
        heading: 'Layout and route data',
        body: [
          'Layouts and the leaf route can each export a loader. Blokd runs loaders from layout to leaf and merges plain-object results into one data object.',
          'Use unique keys for layout data to avoid accidental overwrites.'
        ],
        examples: [
          {
            filename: 'src/routes/_layout.tsx',
            code: "export const loader = async ({ ctx }) => ({\n  session: await ctx.get('auth').readSession()\n});\n\nexport default function Layout(props) {\n  return <main>{props.children}</main>;\n}"
          }
        ]
      },
      {
        heading: 'Data requests',
        body: [
          'Blokd can return route data as JSON for requests that include the data query parameter or ask for application/json instead of text/html.',
          'The default query parameter is __blokd. You can customize it with createPages({ dataQueryParam }).'
        ],
        examples: [
          {
            code: 'fetch("/docs/getting-started?__blokd").then(r => r.json())'
          }
        ],
        warning: 'Loader data is serialized into HTML for document responses. Do not return secrets, private tokens, or raw user records from loaders.'
      }
    ]
  },
  {
    slug: 'forms-and-actions',
    title: 'Forms and Actions',
    summary: 'Use native form submissions and route actions for mutations without client-side routing requirements.',
    category: 'Core concepts',
    sections: [
      {
        heading: 'Native form flow',
        body: [
          'Actions run for POST, PUT, PATCH, and DELETE requests that match a route. The action receives the same Request, params, and Hono context shape as loaders.',
          'Because forms are native HTML, they work without JavaScript and keep progressive enhancement optional.'
        ],
        examples: [
          {
            filename: 'src/routes/contact.tsx',
            code: "import { redirect } from 'blokd/server';\n\nexport const action = async ({ request, ctx }) => {\n  const form = await request.formData();\n  await ctx.get('mail').send({\n    email: String(form.get('email') ?? ''),\n    message: String(form.get('message') ?? '')\n  });\n  redirect('/thanks', 303);\n};\n\nexport default function ContactPage() {\n  return (\n    <form method=\"post\">\n      <input name=\"email\" type=\"email\" required />\n      <textarea name=\"message\" required />\n      <button>Send</button>\n    </form>\n  );\n}"
          }
        ]
      },
      {
        heading: 'Action return values',
        body: [
          'Actions can return Response objects, strings, numbers, booleans, renderable JSX, plain objects, null, or undefined.',
          'Plain objects are normalized to JSON. null and undefined become 204 No Content. Redirects throw a response using redirect().'
        ],
        examples: [
          {
            code: "export const action = async ({ request }) => {\n  const form = await request.formData();\n  if (!form.get('email')) return { ok: false, error: 'Email is required' };\n  return { ok: true };\n};"
          }
        ]
      },
      {
        heading: 'Validation and security',
        body: [
          'Blokd intentionally does not wrap validation, CSRF, spam protection, or rate limiting. Add those checks in your action, Hono middleware, or service layer.',
          'Public mutation endpoints should validate every field, reject unexpected input, and avoid long-running work in the request path unless the target runtime supports it.'
        ],
        bullets: [
          'Use 303 redirects after successful browser form submissions.',
          'Return JSON for programmatic clients.',
          'Use httpError(422) or JSON validation errors for invalid data.',
          'Add CSRF or Turnstile-style bot protection for public forms.'
        ]
      }
    ]
  },
  {
    slug: 'layouts-and-metadata',
    title: 'Layouts, Metadata, and Headers',
    summary: 'Compose nested layouts, page metadata, response headers, stylesheet links, and document attributes.',
    category: 'Core concepts',
    sections: [
      {
        heading: 'Layouts',
        body: [
          'A _layout.tsx file wraps every route below its directory. Nested layouts are applied from the root down to the leaf route.',
          'Layouts receive children, data, params, and ctx. They can also export loader, meta, and headers.'
        ],
        examples: [
          {
            filename: 'src/routes/_layout.tsx',
            code: "export const meta = () => ({\n  htmlAttrs: { lang: 'en' },\n  links: [{ rel: 'stylesheet', href: '/assets/client.css' }]\n});\n\nexport default function Layout(props) {\n  return (\n    <>\n      <header><a href=\"/\">Blokd</a></header>\n      <main>{props.children}</main>\n    </>\n  );\n}"
          }
        ]
      },
      {
        heading: 'Metadata',
        body: [
          'meta() returns a MetaDescriptor. Later descriptors override title and description, while htmlAttrs, bodyAttrs, meta, links, and scripts are merged.',
          'Use route metadata for page titles, descriptions, Open Graph tags, preload links, and theme attributes.'
        ],
        examples: [
          {
            code: "export const meta = ({ data }) => ({\n  title: `${data.post.title} | Blog`,\n  description: data.post.excerpt,\n  meta: [\n    { property: 'og:title', content: data.post.title },\n    { name: 'robots', content: data.post.draft ? 'noindex' : 'index,follow' }\n  ]\n});"
          }
        ]
      },
      {
        heading: 'Headers',
        body: [
          'headers() can add response headers after loader data is available. Use it for route-specific cache policy, robots directives, or custom diagnostics.',
          'Global security headers usually belong in Hono middleware so they apply to pages, APIs, assets, and errors consistently.'
        ],
        examples: [
          {
            code: "export const headers = () => ({\n  'cache-control': 'public, max-age=60',\n  'x-route-kind': 'docs'\n});"
          }
        ]
      }
    ]
  },
  {
    slug: 'error-boundaries',
    title: 'Error and 404 Boundaries',
    summary: 'Render nearest not-found and error boundaries for document requests without making them public routes.',
    category: 'Core concepts',
    sections: [
      {
        heading: 'Boundary files',
        body: [
          'Blokd supports private _404.tsx and _error.tsx files. They are discovered by the route manifest but are not routable pages.',
          'Nearest boundary wins, so an admin area can have different error UI from the public site.'
        ],
        examples: [
          {
            code: 'src/routes/_404.tsx\nsrc/routes/_error.tsx\nsrc/routes/admin/_404.tsx\nsrc/routes/admin/_error.tsx'
          }
        ]
      },
      {
        heading: 'Not found',
        body: [
          'Throw notFound() from a loader when the requested record does not exist. Unmatched paths use the first available root 404 boundary.'
        ],
        examples: [
          {
            filename: 'src/routes/_404.tsx',
            code: "export const meta = () => ({ title: 'Not Found' });\n\nexport default function NotFoundPage() {\n  return <h1>Page not found</h1>;\n}"
          }
        ]
      },
      {
        heading: 'Unexpected errors',
        body: [
          'A thrown httpError(500) or unexpected loader/render error renders the nearest _error.tsx for document requests.',
          'Production responses do not serialize stack traces through boundary props.'
        ],
        examples: [
          {
            filename: 'src/routes/_error.tsx',
            code: "export const meta = ({ error }) => ({ title: 'Error' });\n\nexport default function ErrorPage(props) {\n  return <h1>Error {props.status}</h1>;\n}"
          }
        ]
      }
    ]
  },
  {
    slug: 'resumable-islands',
    title: 'Resumable Islands',
    summary: 'Attach small event handlers to server HTML without hydrating a whole app.',
    category: 'Client',
    sections: [
      {
        heading: 'What Blokd resumes',
        body: [
          'Blokd does not serialize arbitrary closures, promises, class instances, or an entire app graph. It resumes event behavior for a marked island.',
          'The server writes a data-blokd-island wrapper, JSON-safe state, and event handler refs. The browser runtime delegates events and loads handlers on demand.'
        ],
        examples: [
          {
            filename: 'src/components/Estimate.tsx',
            code: "import { Island, on } from 'blokd';\n\nexport function Estimate() {\n  return (\n    <Island name=\"estimate\" state={{ guests: 12, perGuest: 75 }}>\n      <input\n        type=\"range\"\n        name=\"guests\"\n        value=\"12\"\n        onInput={on('/src/resumables/estimate.ts#updateGuests')}\n      />\n      <p data-estimate-output>12 guests</p>\n    </Island>\n  );\n}"
          }
        ]
      },
      {
        heading: 'Register production handlers',
        body: [
          'In beta production apps, register stable handler ids from the client entry unless your built handler modules are intentionally importable by URL.',
          'Use allowRef to narrow which refs the runtime is allowed to execute.'
        ],
        examples: [
          {
            filename: 'src/client.ts',
            code: "import { registerResumable, startResumability } from 'blokd/client';\nimport { updateGuests } from './resumables/estimate';\n\nregisterResumable('/src/resumables/estimate.ts#updateGuests', updateGuests);\nstartResumability({\n  allowRef: ref => ref.startsWith('/src/resumables/'),\n  onError(error) {\n    console.error('[blokd resume]', error);\n  }\n});"
          },
          {
            filename: 'src/resumables/estimate.ts',
            code: "import { defineAction } from 'blokd/resume';\n\ntype EstimateState = { guests: number; perGuest: number };\n\nexport const updateGuests = defineAction<EstimateState>(({ event, state, island }) => {\n  const input = event.target as HTMLInputElement;\n  state.guests = Number(input.value);\n  island?.querySelector('[data-estimate-output]')?.replaceChildren(`${state.guests} guests`);\n});"
          }
        ]
      },
      {
        heading: 'State rules',
        body: [
          'Island state must be JSON-compatible because it is serialized into data attributes and parsed in the browser.',
          'Use ids or plain values in state, then fetch richer data from the handler when needed.'
        ],
        bullets: [
          'Supported: strings, numbers, booleans, null, arrays, and plain objects.',
          'Avoid functions, class instances, DOM nodes, cyclic objects, Maps, Sets, promises, Request, Response, and Hono context values.'
        ]
      }
    ]
  },
  {
    slug: 'client-entry',
    title: 'Client Entry and Enhancement',
    summary: 'Start resumability, register handlers, and add optional navigation/form enhancement where a route needs it.',
    category: 'Client',
    sections: [
      {
        heading: 'Static pages stay static',
        body: [
          'Blokd route analysis marks routes with obvious client markers. createPages() emits entryClient only when the matched route has hasClient !== false.',
          'A docs page with no event handlers can render with CSS and HTML only. A page that imports islands or resumable handlers gets the client entry.'
        ],
        warning: 'The beta analyzer is conservative. False positives can add the client script. False negatives are bugs and should be reported.'
      },
      {
        heading: 'Resumability entry',
        body: [
          'Most apps only need a small client entry that registers handlers and starts delegated events.'
        ],
        examples: [
          {
            filename: 'src/client.ts',
            code: "import { registerResumable, startResumability } from 'blokd/client';\nimport { updateGuests } from './resumables/estimate';\n\nregisterResumable('/src/resumables/estimate.ts#updateGuests', updateGuests);\nstartResumability({ allowRef: ref => ref.startsWith('/src/resumables/') });"
          }
        ]
      },
      {
        heading: 'Optional enhancement hooks',
        body: [
          'blokd/client also exports enhance(), a small helper for intercepting same-origin navigation and form submissions.',
          'Use it when you want to layer app-specific behavior on top of native links and forms. It does not impose a router.'
        ],
        examples: [
          {
            code: "import { enhance } from 'blokd/client';\n\nconst dispose = enhance({\n  async onNavigate(url) {\n    location.href = url.href;\n  },\n  async onSubmit(form, submitter) {\n    const response = await fetch(form.action, {\n      method: form.method,\n      body: new FormData(form)\n    });\n    console.log(response.status, submitter?.getAttribute('name'));\n  }\n});"
          }
        ]
      }
    ]
  },
  {
    slug: 'reactivity',
    title: 'Signals and JSX Runtime',
    summary: 'Use Solid-familiar primitives for small browser islands while server pages remain plain JSX.',
    category: 'Client',
    sections: [
      {
        heading: 'Signals',
        body: [
          'Blokd exports small reactive primitives for browser-side behavior. They are intentionally familiar to Solid users: signal(), memo(), effect(), cleanup(), batch(), untrack(), root(), and dispose().',
          'The recommended beta model is not full-app hydration. Use signals inside islands or custom client entry code.'
        ],
        examples: [
          {
            code: "import { signal, memo, effect } from 'blokd';\n\nconst [count, setCount] = signal(0);\nconst doubled = memo(() => count() * 2);\n\neffect(() => {\n  console.log('count changed', count(), doubled());\n});\n\nsetCount(previous => previous + 1);"
          }
        ]
      },
      {
        heading: 'Control flow',
        body: [
          'Show and For render on the server and can become dynamic in the browser when used inside a client-rendered scope.',
          'For server routes, they are mostly convenience helpers for conditional markup and arrays.'
        ],
        examples: [
          {
            code: "import { For, Show } from 'blokd';\n\nexport default function TeamPage(props) {\n  return (\n    <section>\n      <Show when={props.data.members.length > 0} fallback={<p>No members yet.</p>}>\n        <For each={props.data.members}>{member => <p>{member.name}</p>}</For>\n      </Show>\n    </section>\n  );\n}"
          }
        ]
      },
      {
        heading: 'SSR safety',
        body: [
          'SSR escapes text and attributes by default. innerHTML and outerHTML are blocked during SSR and DOM creation to avoid accidental unsanitized HTML injection.',
          'Use explicit sanitization boundaries in application code when you truly need trusted HTML.'
        ]
      }
    ]
  },
  {
    slug: 'hono-integration',
    title: 'Hono Integration',
    summary: 'Use Hono middleware, context variables, API routes, and Blokd pages in one request pipeline.',
    category: 'Server',
    sections: [
      {
        heading: 'Mounting pages',
        body: [
          'createPages() returns a Hono app. Mount it with app.route() after middleware and before or after API routes according to your URL design.',
          'Because the Hono context is passed into loaders and actions, middleware can attach request ids, authenticated users, service clients, or environment bindings.'
        ],
        examples: [
          {
            filename: 'src/worker.ts',
            code: "import { Hono } from 'hono';\nimport { createPages } from 'blokd/hono';\nimport routes from 'virtual:blokd/routes';\n\nconst app = new Hono();\n\napp.use('*', async (c, next) => {\n  c.set('requestId', crypto.randomUUID());\n  await next();\n});\n\napp.get('/api/health', c => c.json({ ok: true, runtime: 'cloudflare-workers' }));\napp.route('/', createPages({ routes, entryClient: '/assets/client.js' }));\n\nexport default app;"
          }
        ]
      },
      {
        heading: 'createPages options',
        body: [
          'routes is required. entryClient is emitted only for routes that need client code. dataQueryParam changes the JSON data query key. stream opts document responses into Web Streams. onError lets you centralize non-document error responses.'
        ],
        examples: [
          {
            code: "app.route('/', createPages({\n  routes,\n  entryClient: '/assets/client.js',\n  dataQueryParam: '__data',\n  stream: true,\n  onError(error, ctx) {\n    console.error(ctx.get('requestId'), error);\n    return new Response('Internal Server Error', { status: 500 });\n  }\n}));"
          }
        ]
      },
      {
        heading: 'API routes stay Hono',
        body: [
          'Use Hono for JSON APIs, webhooks, auth callbacks, and health checks. Blokd does not try to replace the HTTP layer.'
        ],
        examples: [
          {
            code: "app.post('/api/newsletter', async c => {\n  const body = await c.req.json();\n  await c.env.QUEUE.send(body);\n  return c.json({ ok: true });\n});"
          }
        ]
      }
    ]
  },
  {
    slug: 'server-helpers',
    title: 'Server Helpers',
    summary: 'Return JSON, HTML, redirects, HTTP errors, metadata, and SSR strings from Blokd server utilities.',
    category: 'Server',
    sections: [
      {
        heading: 'Responses and errors',
        body: [
          'blokd/server exports helpers that work in route modules, API handlers, tests, and custom rendering code.',
          'redirect(), notFound(), and httpError() throw HttpError instances so createPages() can route them through document boundaries where appropriate.'
        ],
        examples: [
          {
            code: "import { redirect, notFound, httpError, json, html } from 'blokd/server';\n\nexport const loader = async ({ params }) => {\n  const page = await loadPage(params.slug);\n  if (!page) notFound();\n  if (page.private) httpError(403, 'Forbidden');\n  return { page };\n};\n\nexport const action = async () => redirect('/thanks', 303);\nexport const api = () => json({ ok: true });\nexport const fragment = () => html('<p>Trusted HTML from your app</p>');"
          }
        ]
      },
      {
        heading: 'SSR utilities',
        body: [
          'renderToString(), renderDocument(), renderHead(), mergeMeta(), escapeHtml(), and safeJsonScript() are exported for tests, custom responses, and framework integration work.'
        ],
        examples: [
          {
            code: "import { renderToString } from 'blokd/server';\n\nconst html = renderToString(<strong>Server rendered</strong>);"
          }
        ]
      },
      {
        heading: 'Redirect validation',
        body: [
          'redirect() accepts 301, 302, 303, 307, and 308. It rejects CR/LF characters in Location to prevent header injection.'
        ]
      }
    ]
  },
  {
    slug: 'cloudflare-workers',
    title: 'Cloudflare Workers',
    summary: 'Run Blokd as a Worker script and serve compiled CSS and assets with Workers static assets.',
    category: 'Deployment',
    sections: [
      {
        heading: 'Reference deployment shape',
        body: [
          'The blokd.dev site is the reference Workers deployment shape. It builds CSS and future client chunks as static assets, then runs document requests through a Hono Worker entry.',
          'Workers static assets should use not_found_handling: none so Blokd can render _404.tsx boundaries for document requests.'
        ],
        examples: [
          {
            filename: 'wrangler.jsonc',
            code: '{\n  "name": "blokd-dev-site",\n  "main": "./dist/worker/entry-worker.js",\n  "assets": {\n    "directory": "./dist/client",\n    "binding": "ASSETS",\n    "not_found_handling": "none"\n  },\n  "compatibility_date": "2026-06-01"\n}'
          }
        ]
      },
      {
        heading: 'Build and validate',
        body: [
          'Build the client assets first, then the Worker entry. Use smoke tests before deploying and Wrangler dry-run before touching a real custom domain.'
        ],
        examples: [
          {
            code: 'pnpm build:site\npnpm smoke:site\npnpm --filter blokd-dev-site deploy:dry-run\npnpm --filter blokd-dev-site deploy'
          }
        ]
      },
      {
        heading: 'Serving static assets',
        body: [
          'The Worker should let the ASSETS binding serve generated files like /assets/client.css and /favicon.svg. Blokd should own route documents and error pages.',
          'Long-lived immutable caching belongs on hashed assets. HTML responses should avoid immutable caching unless your application has explicit static generation rules.'
        ],
        warning: 'Add the real blokd.dev route only after the Cloudflare zone is configured and the dry run has passed.'
      }
    ]
  },
  {
    slug: 'node-and-other-runtimes',
    title: 'Node and Other Runtimes',
    summary: 'Deploy Blokd through Hono runtime adapters while testing each target’s asset and environment behavior.',
    category: 'Deployment',
    sections: [
      {
        heading: 'Node server',
        body: [
          'Node deployment uses Hono’s Node server adapter. The basic restaurant example demonstrates this shape.',
          'Serve dist/client assets yourself or with a static middleware, then route document requests through createPages().'
        ],
        examples: [
          {
            code: 'pnpm build:restaurant\npnpm start:restaurant'
          }
        ]
      },
      {
        heading: 'Edge runtimes',
        body: [
          'Blokd’s server contract is Web-standard Request and Response through Hono. That keeps edge deployment possible, but each target has different filesystem access, environment bindings, streaming behavior, and static asset serving.',
          'Treat a new runtime as a port: build, smoke, exercise forms, verify boundaries, and check generated client scripts.'
        ],
        bullets: [
          'Use Hono’s runtime-specific adapter.',
          'Map static assets to the host’s asset serving primitive.',
          'Use runtime environment variables in Hono middleware and services.',
          'Avoid serializing secrets through loaders or island state.'
        ]
      }
    ]
  },
  {
    slug: 'security',
    title: 'Security Model',
    summary: 'Understand framework guardrails and the application responsibilities that remain with your Hono app.',
    category: 'Production',
    sections: [
      {
        heading: 'Framework guardrails',
        body: [
          'Blokd escapes SSR text and attributes by default, blocks innerHTML and outerHTML, escapes JSON embedded in scripts, validates redirects, and rejects unsafe resumable dynamic import schemes.',
          'These are guardrails, not a complete application security layer.'
        ],
        bullets: [
          'safeJsonScript() escapes <, >, &, U+2028, and U+2029.',
          'redirect() rejects invalid statuses and CR/LF injection.',
          'httpError() accepts only 4xx and 5xx statuses.',
          'startResumability() supports allowRef() for production import allowlists.'
        ]
      },
      {
        heading: 'Application responsibilities',
        body: [
          'Your app must still validate input, protect mutation endpoints, configure cookies, set security headers, and keep dependencies updated.',
          'Blokd intentionally leaves security middleware in Hono so it applies across pages, APIs, and assets consistently.'
        ],
        examples: [
          {
            code: "app.use('*', secureHeaders());\napp.use('/reservations', rateLimit());\napp.use('*', async (c, next) => {\n  c.set('requestId', crypto.randomUUID());\n  await next();\n});"
          }
        ]
      },
      {
        heading: 'CSP and resumability',
        body: [
          'The recommended production mode is registered refs: the HTML contains stable ids, but handlers are registered from the trusted client bundle before interaction.',
          'That mode works with a strict same-origin module-script CSP and does not need unsafe-inline.'
        ],
        bullets: [
          "Use script-src 'self' for the Blokd client entry and generated route-local island entries.",
          'Keep object-src none, base-uri none, form-action self, and connect-src self unless your app needs more.',
          'Only expose importable handler chunks when you intentionally want refs to dynamic-import public browser modules.',
          'When using importable chunks, keep allowRef scoped to the exact public asset path shape.'
        ],
        examples: [
          {
            code: "default-src 'self';\nbase-uri 'none';\nobject-src 'none';\nframe-ancestors 'none';\nscript-src 'self';\nstyle-src 'self';\nimg-src 'self' data:;\nconnect-src 'self';\nform-action 'self';"
          }
        ]
      },
      {
        heading: 'Data serialization',
        body: [
          'Loader data and island state can be serialized to the browser. Do not put secrets, private tokens, raw session objects, or privileged service credentials in either place.'
        ],
        warning: 'If a value must not be visible in page source, do not return it from a loader and do not include it in island state.'
      }
    ]
  },
  {
    slug: 'known-limitations',
    title: 'Known Limitations',
    summary: 'The beta constraints around JSX runtime, hydration, route analysis, resumable refs, browsers, and runtimes.',
    category: 'Production',
    sections: [
      {
        heading: 'JSX runtime',
        body: [
          'The Vite transform emits cached DOM templates for static intrinsic JSX.',
          'Dynamic JSX, components, spreads, events, and refs still use the small runtime path. Broader compiler coverage remains future work.'
        ]
      },
      {
        heading: 'Hydration model',
        body: [
          'hydrate() claims existing SSR nodes and uses marker comments for dynamic regions.',
          'It is intended for focused interactive roots. The recommended beta model remains HTML-first SSR plus resumable islands, not full-app hydration.'
        ]
      },
      {
        heading: 'Static-route analysis',
        body: [
          'The Vite plugin conservatively scans route files and static relative imports for client markers such as event attributes, signal, effect, Island, resumable, and startResumability.',
          'False positives add the client script. False negatives are considered bugs because required browser code would be omitted.'
        ]
      },
      {
        heading: 'Resumable refs',
        body: [
          'Refs such as /src/resumables/private-dining.ts#updateGuests are stable ids, not a promise that source files are served in production.',
          'Register handlers from the client entry for beta production apps unless you intentionally expose importable handler chunks.',
          'Registered refs are the CSP-friendly production path. Importable chunks should keep allowRef narrow and script-src limited to trusted origins.'
        ]
      }
    ]
  },
  {
    slug: 'testing-and-release',
    title: 'Testing and Release',
    summary: 'Run the validation gates Blokd should pass before publishing each beta build.',
    category: 'Production',
    sections: [
      {
        heading: 'Repository checks',
        body: [
          'Run the full validation set from a clean install before publishing a beta or deploying the public website.',
          'The current gates cover TypeScript, unit tests, package shape, size budgets, examples, Worker smoke tests, browser integration tests, and package dry-run output.'
        ],
        examples: [
          {
            code: 'corepack enable\npnpm install\npnpm check\npnpm build:restaurant\npnpm smoke:restaurant\npnpm build:site\npnpm smoke:site\npnpm test:browser\npnpm pack:dry-run'
          }
        ]
      },
      {
        heading: 'Website checks',
        body: [
          'The blokd.dev site should build, pass the Worker smoke test, and pass a Wrangler dry run before deployment.',
          'Visual changes should be checked on desktop and mobile so code examples, nav, cards, and docs prose do not overflow.'
        ],
        examples: [
          {
            code: 'pnpm build:site\npnpm smoke:site\npnpm --filter blokd-dev-site deploy:dry-run'
          }
        ]
      },
      {
        heading: 'Release notes',
        body: [
          'Each beta release should record the browser summary, package tarball contents, known limitations, API changes, and whether any experimental behavior changed.'
        ],
        bullets: [
          'Document new public exports.',
          'Document breaking changes to route module contracts.',
          'List limitations that affect production use.',
          'Keep examples and docs aligned with the package version.'
        ]
      }
    ]
  }
];

export function getDoc(slug: string): DocPage | undefined {
  return docs.find(doc => doc.slug === slug);
}

export function docsByCategory(): Array<{ category: string; docs: DocPage[] }> {
  return docCategories
    .map(category => ({ category, docs: docs.filter(doc => doc.category === category) }))
    .filter(group => group.docs.length > 0);
}
